version: 0.3
os: linux
files:
  - source: target/demo-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/app/
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ec2-user
